# Generated by Django 3.0.6 on 2020-09-01 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL')),
                ('short_desc', models.TextField(max_length=1500, verbose_name='Short Description')),
                ('desc', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/blog')),
                ('sort', models.IntegerField(default=0)),
                ('active', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=900)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/pages', verbose_name='Cover image')),
                ('show_image', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('content', models.TextField(blank=True)),
                ('static', models.CharField(choices=[('contact', 'contact'), ('blog', 'blog'), ('null', 'null')], default='null', max_length=25)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=900)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('active', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('to_menu', models.CharField(choices=[('0', 'Dont show'), ('1', 'Show')], default='1', max_length=1, verbose_name='Show to menu')),
                ('sort', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('file2', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('file3', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('video_url', models.SlugField(max_length=250, null=True, verbose_name='YouTube Video ID')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL')),
                ('short_desc', models.TextField(max_length=1500, verbose_name='Short Description')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='media/service')),
                ('sort', models.ImageField(default=0, upload_to='')),
                ('active', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=900)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
