# Generated by Django 3.0.6 on 2020-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='file',
            field=models.FileField(null=True, upload_to='media/pages'),
        ),
    ]
