# Generated by Django 3.0.6 on 2020-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_pages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='file',
            field=models.FileField(null=True, upload_to='media/pages/files'),
        ),
    ]
