# Generated by Django 3.0.6 on 2020-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_auto_20200728_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='file2',
            field=models.FileField(null=True, upload_to='media/pages/files', verbose_name='Attach file'),
        ),
        migrations.AddField(
            model_name='pages',
            name='file3',
            field=models.FileField(null=True, upload_to='media/pages/files', verbose_name='Attach file'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='file',
            field=models.FileField(null=True, upload_to='media/pages/files', verbose_name='Attach file'),
        ),
    ]
