# Generated by Django 3.0.6 on 2020-09-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_gruz_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gruz',
        ),
    ]
