# Generated by Django 3.0.6 on 2020-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='baner_text',
        ),
    ]
