# Generated by Django 3.0.6 on 2020-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_delete_gruz'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media\\gallery')),
                ('alt', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
