# Generated by Django 3.0.6 on 2020-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_remove_about_baner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='baner_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
