# Generated by Django 3.0.6 on 2020-09-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.gallery'),
        ),
    ]
