# Generated by Django 3.0.6 on 2020-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_pages_page_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='page_gallery',
        ),
        migrations.AddField(
            model_name='pages',
            name='page_gallery',
            field=models.ManyToManyField(null=True, to='solar.gallery'),
        ),
    ]
