# Generated by Django 3.0.6 on 2020-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_delete_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.SlugField(blank=True, max_length=250, null=True, verbose_name='Google map link')),
                ('adress', models.CharField(max_length=250)),
                ('phone1', models.IntegerField(blank=True, max_length=20)),
                ('phone2', models.IntegerField(blank=True, max_length=20)),
                ('email1', models.EmailField(blank=True, max_length=200)),
                ('email2', models.EmailField(blank=True, max_length=200)),
            ],
        ),
    ]
