# Generated by Django 3.0.6 on 2020-09-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_auto_20200901_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='page_gallery',
        ),
        migrations.AddField(
            model_name='pages',
            name='page_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.gallery'),
        ),
    ]
