# Generated by Django 3.0.6 on 2020-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adress_icon',
            field=models.ImageField(null=True, upload_to='media/pages'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_icon',
            field=models.ImageField(null=True, upload_to='media/pages'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_icon',
            field=models.ImageField(null=True, upload_to='media/pages'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
