# Generated by Django 3.0.6 on 2020-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_auto_20200901_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='test',
            field=models.CharField(blank=True, max_length=456),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_gallery',
            field=models.ManyToManyField(blank=True, to='solar.gallery'),
        ),
    ]
