# Generated by Django 3.0.6 on 2020-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_auto_20200918_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Google map link'),
        ),
    ]
