# Generated by Django 3.0.6 on 2020-09-23 17:53

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_auto_20200920_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, null=True, unique=True, verbose_name='Change URL')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, null=True, unique=True, verbose_name='Change URL')),
                ('cod', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='media/products/file', validators=[django.core.validators.FileExtensionValidator(['.pdf'])], verbose_name='Attach PDF file')),
                ('image', models.ImageField(upload_to='media/products')),
                ('desc1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('desc2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Product Propertis')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='solar.Category')),
                ('related_products', models.ManyToManyField(blank=True, null=True, related_name='_product_related_products_+', to='solar.Product')),
            ],
        ),
    ]
