# Generated by Django 3.0.6 on 2020-09-24 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/products/file', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Attach PDF file'),
        ),
    ]
