# Generated by Django 3.0.6 on 2020-09-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_pages_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='test',
        ),
    ]
