# Generated by Django 3.0.6 on 2020-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_auto_20200924_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1),
        ),
    ]
