# Generated by Django 3.0.6 on 2020-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_remove_pages_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='test',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
