# Generated by Django 3.0.6 on 2020-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0014_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc2',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
    ]
