# Generated by Django 3.0.6 on 2020-09-07 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0015_remove_pages_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
