# Generated by Django 3.0.6 on 2020-10-08 14:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0016_auto_20200925_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_home_block_1',
            field=models.CharField(choices=[('0', 'Dont show'), ('1', 'Show')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='show_home_block_2',
            field=models.CharField(choices=[('0', 'Dont show'), ('1', 'Show')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Propertis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='solar.Product'),
        ),
    ]
