# Generated by Django 3.0.6 on 2020-09-08 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0017_auto_20200907_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
