# Generated by Django 3.0.6 on 2020-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0017_auto_20201008_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
    ]
