# Generated by Django 3.0.6 on 2020-10-13 12:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0018_fotterlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_ru',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
