# Generated by Django 3.0.6 on 2020-10-19 16:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0019_auto_20201013_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_hy',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
