# Generated by Django 3.0.6 on 2020-11-12 17:01

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0020_auto_20201019_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='blog',
            name='desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='desc_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_description_hy',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keywords_hy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title_hy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_desc_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_desc_hy',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_desc_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_hy',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_description_hy',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_keywords_hy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_title_hy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_hy',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords_hy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title_hy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_hy',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_hy',
            field=models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_hy',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=65, null=True, unique=True, verbose_name='Change URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/pages', verbose_name='Cover image')),
                ('show_image', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('static', models.CharField(choices=[('contact', 'contact'), ('blog', 'blog'), ('null', 'null')], default='null', max_length=25)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=900)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('active', models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1)),
                ('to_menu', models.CharField(choices=[('0', 'Dont show'), ('1', 'Show')], default='1', max_length=1, verbose_name='Show to menu')),
                ('sort', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('file2', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('file3', models.FileField(blank=True, null=True, upload_to='media/pages/files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'rtf', 'xlsx'])], verbose_name='Attach file')),
                ('video_url', models.SlugField(blank=True, max_length=250, null=True, verbose_name='YouTube Video ID')),
                ('main_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.pages')),
                ('page_gallery', models.ManyToManyField(blank=True, to='solar.gallery')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
