# Generated by Django 3.0.6 on 2020-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0020_auto_20200909_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/slides')),
                ('alt', models.CharField(blank=True, max_length=150)),
                ('img_title', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('btn_link', models.URLField(blank=True)),
                ('btn_title', models.CharField(blank=True, max_length=100)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
    ]
