# Generated by Django 3.0.6 on 2020-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0021_auto_20200912_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslide',
            name='active',
            field=models.CharField(choices=[('0', 'Disabled'), ('1', 'Active')], default='1', max_length=1),
        ),
    ]
