# Generated by Django 3.0.6 on 2020-11-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0023_auto_20201112_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='main_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.pages'),
        ),
    ]
