# Generated by Django 3.0.6 on 2020-11-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0027_auto_20201120_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='main_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='solar.pages'),
        ),
    ]
