# Generated by Django 3.0.6 on 2020-11-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0028_auto_20201120_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='main_page',
        ),
    ]
